### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Jakousa** [altrangaj/FULLSTACK_HARJOITUSTYO#2]
# Katselmointi

### Mitä tein

* 20.12.2019 klo ~17:00

* Käytin molempia sekä vanhaa että uutta sovellusta

* Rekisteröidyin ja kirjauduin sisään

* Tein kanavan 

### Kokemus

* Ensimmäinen kuva *ei* näytä yhteen lyödyiltä nyrkeiltä isommalla ruudulla

* Sivu oli vaikea bookmarkata - page title ja favicon ovat jääneet unohduksiin.

* Enter ei lähetä viestejä :(

* Olisi kiva olla haku/filtteri käyttäjien etsintään kun kanavalle valitaan käyttäjiä

* Oli erittäin vaikea keksiä miten muistiinpanoja/postit lappuja lisätään ruudulle. Ehkä käyttökokemusta voi vielä parannella. Onneksi käyttöohje opasti

* Ainakaan yhdellä käyttäjällä useassa ikkunassa ei laput siirtyneet tai ilmestyneet toisaalla niitä luodessa tai siirtäessä (bugi?)

## Koodi

* Koodi löytyy juuri sieltä mistä pitää!

* Backendissä harkitse käyttäväsi https://www.npmjs.com/package/express-async-errors sen sijaan että copy pasteat kaikkialle identtisen try catchin.

* palvelimen index.js sisältää aikamoisen switch casen. Voisikohan sitä jotenkin pilkkoa ja copy-paste koodista päästä eroon?

* Lue https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html
  * ja sovella sitä tähän: https://github.com/altrangaj/FULLSTACK_HARJOITUSTYO/blob/6528d34cf366ec9b4f33250581de33535a3d10c8/chat-client/src/components/Chat.js#L54
  * ja moneen muuhunkin paikkaan

* Frontin koodi on aika kivuliasta luettavaa sisennyksen ansiosta. Ei ole vahinko että jsx usein suositellaan 2 välilyönnin sisennystä. Toivottavasti on ultrawide näyttö käytössä

* Rohkeasti curry käyttöön `= user => async dispatch =>` https://github.com/altrangaj/FULLSTACK_HARJOITUSTYO/blob/6528d34cf366ec9b4f33250581de33535a3d10c8/chat-client/src/reducers/channelsReducer.js#L4-L5

* Repositorion nimi ei kuvaa sovellusta.

## Kokonaisuus

* Pienen refaktoroinnin jälkeen sovelluksesta tulee todella esimerkillinen.
  * Laita vielä readme ja sovelluksen nimi ja kuvaus githubin ohjeistuksen mukaiseksi https://guides.github.com/features/wikis/

* Erittäin näppärä sovellus ja kekselijäisyyttä on käytetty ratkaisuissa!

**Comment by altrangaj** [comment]
Sovelluksen kaksi eri versiota eivät synkkaa keskenään, koska ne käyttävät eri backend instanssia. Kylläkin samaa tietokantaa. Eli lappujen liikuttelut päivittyvät kantaan, mutta ei suoraan sovellus versiosta 1 versioon 2. Tämä koskee muutakin toiminnallisuutta.

**Comment by altrangaj** [comment]
Huomioin katselmuksen #2 kokemus ja koodi osioiden kohdat commitissa bed3b1d3969630af29e67907f8b9c9d35abb7d02 sekä korjasin readme-tiedoston. Tein korjaukset sovellus_v2 brachiin, jonka sitten päätin mergetä varsinaiseen. Poistin käyttöohjeen, koska se oli vanhaan versioon ja README.md sisältää päivitetyn ohjeistuksen.
